Fix index bug in ckan 2.9 on rebuild
- Solr 9 and ckan 2.9 bug.
- Do not build index for ckan.extra_resource_fields split.

Error: Indexing record 89/19482024-10-07 19:27:12,955 ERROR [ckan.lib.search] Error while indexing
 dataset 423b1db2-d44f-5dcd-8583-53690064450f: AttributeError("'list' object has no attribute
e 'split'")
2024-10-07 19:27:12,962 ERROR [ckan.lib.search] Traceback (last call last):
  File "/srv/app/src/ckan/ckan/lib/search/__init__.py", line 200, in rebuild
    package_index.update_dict(
  File "/srv/app/src/ckan/ckan/lib/search/index.py", line 109, in update_dict
    self.index_package(pkg_dict, defer_commit)
  File "/srv/app/src/ckan/lib/search/index.py", line 209, in index_package
    in model.resource.get_extra_columns()].
  File "/srv/app/src/ckan/ckan/model/resource.py", line 129, in get_extra_columns
    cls.extra_columns = config.get(
AttributeError: 'list' object does not have 'split' attribute